// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // The CLI (migrate, studio) wants a direct connection: migrations take
  // advisory locks, which a transaction-mode pooler such as Neon's cannot hold.
  // The app itself keeps the pooled DATABASE_URL — see src/lib/db.ts. Locally
  // there is no pooler, so the unpooled variable is simply absent.
  datasource: {
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
